"""remove rrule requirement

Revision ID: 1c29e2ecfa77
Revises: 4db3338f1f9d
Create Date: 2020-08-18 12:24:40.822528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c29e2ecfa77'
down_revision = '4db3338f1f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'rrule',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_events_rend'), 'events', ['rend'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_rend'), table_name='events')
    op.alter_column('events', 'rrule',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
