"""updates

Revision ID: 2871bb36e1ac
Revises: 8b7ac1bd3825
Create Date: 2020-08-17 17:40:34.984779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2871bb36e1ac'
down_revision = '8b7ac1bd3825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('queued_users', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('queued_users', sa.Column('queue_date', sa.DateTime(), nullable=True, server_defaiult=sa.text('now()')))
    op.add_column('queues', sa.Column('auto_accept', sa.Boolean(), nullable=True))
    op.add_column('queues', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('queues', 'auto_approve')
    op.add_column('subscriptions', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'created')
    op.add_column('queues', sa.Column('auto_approve', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('queues', 'created')
    op.drop_column('queues', 'auto_accept')
    op.drop_column('queued_users', 'queue_date')
    op.drop_column('queued_users', 'created')
    op.drop_column('events', 'created')
    op.drop_column('calendars', 'created')
    # ### end Alembic commands ###
