"""updates

Revision ID: 4db3338f1f9d
Revises: 0a284763d2ea
Create Date: 2020-08-17 18:24:57.758115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db3338f1f9d'
down_revision = '0a284763d2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('rend', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'rend')
    # ### end Alembic commands ###
