"""empty message

Revision ID: 77228cb6e1db
Revises: 8c28372096d6
Create Date: 2020-08-17 13:13:39.801863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77228cb6e1db'
down_revision = '8c28372096d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('event_id', table_name='recurring_events')
    op.drop_column('recurring_events', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_events', sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('event_id', 'recurring_events', ['event_id'], unique=True)
    # ### end Alembic commands ###
