"""add event queues

Revision ID: 7bbf1679bb5a
Revises: bc7376188aac
Create Date: 2020-08-15 15:06:04.113756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bbf1679bb5a'
down_revision = 'bc7376188aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queued_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('requested', 'accepted', 'queued', 'rejected', 'blocked', name='queueduserstate'), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('skills')
    op.add_column('profiles', sa.Column('experience_points', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('profiles', sa.Column('show_name', sa.Boolean(), nullable=True))
    op.drop_column('profiles', 'role')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('profiles', sa.Column('role', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('profiles', 'show_name')
    op.drop_column('profiles', 'name')
    op.drop_column('profiles', 'level')
    op.drop_column('profiles', 'experience_points')
    op.create_table('skills',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('profile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='skills_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('queued_users')
    op.drop_table('queues')
    # ### end Alembic commands ###
