"""update recurring


Revision ID: 8432b8f3afe3
Revises: a993efef9845
Create Date: 2020-08-17 11:37:15.372325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8432b8f3afe3'
down_revision = 'a993efef9845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recurring_events', ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_events', type_='unique')
    # ### end Alembic commands ###
