"""add subscriptions

Revision ID: 88bf28635c3a
Revises: e6f5f9c911fe
Create Date: 2020-08-12 00:29:11.357644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bf28635c3a'
down_revision = 'e6f5f9c911fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('public', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendars', 'public')
    # ### end Alembic commands ###
