"""update recurring

Revision ID: 8c28372096d6
Revises: d532c347ecbd
Create Date: 2020-08-17 13:12:43.519678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c28372096d6'
down_revision = 'd532c347ecbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('recur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'recurring_events', ['recur_id'], ['id'])
    op.drop_index('event_id', table_name='recurring_events')
    op.drop_constraint('recurring_events_ibfk_1', 'recurring_events', type_='foreignkey')
    op.drop_column('recurring_events', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_events', sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('recurring_events_ibfk_1', 'recurring_events', 'events', ['event_id'], ['id'])
    op.create_index('event_id', 'recurring_events', ['event_id'], unique=True)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'recur_id')
    # ### end Alembic commands ###
