"""empty message

Revision ID: a993efef9845
Revises: 7bbf1679bb5a
Create Date: 2020-08-17 11:21:24.721661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a993efef9845'
down_revision = '7bbf1679bb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('rrule', sa.String(length=256), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_events_end'), 'recurring_events', ['end'], unique=False)
    op.create_index(op.f('ix_recurring_events_start'), 'recurring_events', ['start'], unique=False)
    op.drop_table('skills')
    op.add_column('calendars', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('experience_points', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('profiles', sa.Column('show_name', sa.Boolean(), nullable=True))
    op.drop_column('profiles', 'role')
    op.add_column('queued_users', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('queues', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('subscriptions', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('meta', sa.JSON(), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'meta')
    op.drop_column('subscriptions', 'meta')
    op.drop_column('queues', 'meta')
    op.drop_column('queued_users', 'meta')
    op.add_column('profiles', sa.Column('role', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('profiles', 'show_name')
    op.drop_column('profiles', 'name')
    op.drop_column('profiles', 'level')
    op.drop_column('profiles', 'experience_points')
    op.drop_column('events', 'meta')
    op.drop_column('calendars', 'meta')
    op.create_table('skills',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('profile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='skills_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_recurring_events_start'), table_name='recurring_events')
    op.drop_index(op.f('ix_recurring_events_end'), table_name='recurring_events')
    op.drop_table('recurring_events')
    # ### end Alembic commands ###
