"""update recurring

Revision ID: b6026e680880
Revises: 77228cb6e1db
Create Date: 2020-08-17 16:20:09.573070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6026e680880'
down_revision = '77228cb6e1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_events')
    op.add_column('events', sa.Column('rrule', sa.Text(), nullable=False))
    op.drop_constraint('events_ibfk_2', 'events', type_='foreignkey')
    op.drop_column('events', 'recur_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('recur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('events_ibfk_2', 'events', 'recurring_events', ['recur_id'], ['id'])
    op.drop_column('events', 'rrule')
    op.create_table('recurring_events',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('rrule', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('meta', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
